version: 1  
llm:
  gemini:
    model: 'gemini-3-flash-preview'
    temperature: 0.7
    max_retries: 2

db:
  sqlite:
    examples_file: 'sql_examples.json'
    queries_file: 'sql_queries.json'
    prompts_file: 'sql_prompts.json'


use_llm: gemini
use_db: sqlite


